# Generated by Django 4.0.6 on 2023-04-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='detalhes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saída', 'Saída')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
