# Generated by Django 4.0.6 on 2023-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_registroponto_detalhes_registroponto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saída', 'Saída'), ('excessao', 'excessãoExcessão')], max_length=10),
        ),
    ]
