# Generated by Django 4.0.6 on 2023-04-25 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_alter_registroponto_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 12, 35, 41, 628543)),
        ),
    ]
