# Generated by Django 4.0.6 on 2023-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_alter_registroponto_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'entrada'), ('Saída', 'saída'), ('Exceção(entrada)', 'exceçao(entrada)'), ('Exceção(saída)', 'exceçao(saída)'), ('Férias', 'férias)')], max_length=20),
        ),
    ]
