# Generated by Django 4.0.6 on 2023-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0006_alter_registroponto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'entrada'), ('Saída', 'saída'), ('Exceção(entrada)', 'exceçao(entrada)'), ('Exceção(saída)', 'exceçao(saída)'), ('Férias', 'férias')], max_length=20),
        ),
    ]
